server:
  port: 8090
spring:
  application:
    name : fraud
  datasource:
    username: 'root'
    url: jdbc:postgresql://localhost:5432/fraud
    password: '123sa'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
      show-sql: 'true'